update grub-1.99-evms-crap-alt.patch

diff --git a/grub-1.99-evms-crap-alt.patch b/grub-1.99-evms-crap-alt.patch
--- a/grub-1.99-evms-crap-alt.patch
+++ b/grub-1.99-evms-crap-alt.patch
@@ -1,7 +1,7 @@
-diff -ur grub2/kern/emu/getroot.c grub2.new/kern/emu/getroot.c
---- grub2/kern/emu/getroot.c	2010-08-02 19:44:02 +0000
-+++ grub2.new/kern/emu/getroot.c	2011-05-03 11:28:38 +0000
-@@ -449,6 +449,31 @@
+diff -urN grub2/grub-core/kern/emu/getroot.c grub2.new/grub-core/kern/emu/getroot.c
+--- grub2/grub-core/kern/emu/getroot.c	2011-05-23 10:41:13 +0000
++++ grub2.new/grub-core/kern/emu/getroot.c	2011-05-23 10:39:35 +0000
+@@ -529,6 +529,31 @@
  
  #endif /* __CYGWIN__ */
  
@@ -33,17 +33,23 @@ diff -ur grub2/kern/emu/getroot.c grub2.new/kern/emu/getroot.c
  char *
  grub_guess_root_device (const char *dir)
  {
-@@ -535,6 +560,9 @@
+@@ -596,6 +621,7 @@
+ #ifdef __linux__
+   if (!os_dev)
+     os_dev = grub_find_root_device_from_mountinfo (dir, NULL);
++  workaround_evms(os_dev);
+ #endif /* __linux__ */
+ 
+ #if defined(HAVE_LIBZFS) && defined(HAVE_LIBNVPAIR)
+@@ -627,6 +653,7 @@
  
    /* This might be truly slow, but is there any better way?  */
-   os_dev = find_root_device ("/dev", st.st_dev);
-+
+   os_dev = grub_find_device ("/dev", dev);
 +  workaround_evms(os_dev);
-+
  #endif
  #endif /* !__GNU__ */
  
-@@ -786,6 +814,8 @@
+@@ -900,6 +927,8 @@
        grub_dev = grub_util_biosdisk_get_grub_dev (os_dev);
      }
  
@@ -52,40 +58,31 @@ diff -ur grub2/kern/emu/getroot.c grub2.new/kern/emu/getroot.c
    return grub_dev;
  }
  
-diff -ur grub2/util/grub-install.in grub2.new/util/grub-install.in
---- grub2/util/grub-install.in	2010-08-04 03:40:54 +0000
-+++ grub2.new/util/grub-install.in	2011-05-03 11:29:55 +0000
-@@ -319,13 +319,14 @@
+diff -urN grub2/util/grub-install.in grub2.new/util/grub-install.in
+--- grub2/util/grub-install.in	2011-04-03 13:36:21 +0000
++++ grub2.new/util/grub-install.in	2011-05-23 10:43:30 +0000
+@@ -458,13 +458,14 @@
  
  # Write device to a variable so we don't have to traverse /dev every time.
- grub_device=`$grub_probe --target=device ${grubdir}` || exit 1
+ grub_device="`"$grub_probe" --device-map="${device_map}" --target=device "${grubdir}"`" || exit 1
 +grub_device_fs=`echo $grub_device | sed 's|/dev/mapper/\([sv]d\)|/dev/\1|g' `
  
- if ! test -f ${grubdir}/grubenv; then
-     $grub_editenv ${grubdir}/grubenv create
+ if ! test -f "${grubdir}"/grubenv; then
+     "$grub_editenv" "${grubdir}"/grubenv create
  fi
  
  # Create the core image. First, auto-detect the filesystem module.
--fs_module=`$grub_probe --target=fs --device ${grub_device}`
-+fs_module=`$grub_probe --target=fs --device ${grub_device_fs}`
- if test "x$fs_module" = x -a "x$modules" = x; then
-     echo "Auto-detection of a filesystem module failed." 1>&2
-     echo "Please specify the module with the option \`--modules' explicitly." 1>&2
-@@ -377,7 +378,7 @@
-     grub_drive="`echo ${grub_drive} | sed -e s/,[a-z0-9,]*//g`"
-     if [ "$disk_module" = ata ] ; then
+-fs_module="`"$grub_probe" --device-map="${device_map}" --target=fs --device "${grub_device}"`"
++fs_module="`"$grub_probe" --device-map="${device_map}" --target=fs --device "${grub_device_fs}"`"
+ if test "x$fs_module" = x ; then
+     echo "Auto-detection of a filesystem of ${grub_device} failed." 1>&2
+     echo "Try with --recheck." 1>&2
+@@ -524,7 +525,7 @@
+     grub_drive="`echo "${grub_drive}" | sed -e s/,[a-z0-9,]*//g`"
+     if [ "$disk_module" = ata ] || [ "x${grub_drive}" != "x${install_drive}" ] || ([ "x$platform" != xefi ] && [ "x$platform" != xpc ] && [ x"${target_cpu}-${platform}" != x"sparc64-ieee1275" ]) ; then
          # generic method (used on coreboot and ata mod)
--        uuid="`$grub_probe --target=fs_uuid --device ${grub_device}`"
-+        uuid="`$grub_probe --target=fs_uuid --device ${grub_device_fs}`"
+-        uuid="`"$grub_probe" --device-map="${device_map}" --target=fs_uuid --device "${grub_device}"`"
++        uuid="`"$grub_probe" --device-map="${device_map}" --target=fs_uuid --device "${grub_device_fs}"`"
          if [ "x${uuid}" = "x" ] ; then
-           echo "UUID needed with ata mod, but the filesystem containing ${grubdir} does not support UUIDs." 1>&2
-           exit 1
-@@ -387,7 +388,7 @@
- 	config_opt="-c ${grubdir}/load.cfg "
-         modules="$modules search_fs_uuid"
-     elif [ "x${grub_drive}" != "x${install_drive}" ] ; then
--        uuid="`$grub_probe --target=fs_uuid --device ${grub_device}`"
-+        uuid="`$grub_probe --target=fs_uuid --device ${grub_device_fs}`"
-         if [ "x${uuid}" = "x" ] ; then
-           echo "You attempted a cross-disk install, but the filesystem containing ${grubdir} does not support UUIDs." 1>&2
-           exit 1
+           if [ "x$platform" != xefi ] && [ "x$platform" != xpc ] && [ x"${target_cpu}-${platform}" != x"sparc64-ieee1275" ]; then
+              echo "UUID needed with $platform, but the filesystem containing ${grubdir} does not support UUIDs." 1>&2
