2.02-alt12%ubt
- add ia32 EFI support for x86_64 platforms
  + add embedded config into ia32 EFI coreimage
  + rename x64 EFI binary to grubx64.efi
  + add grub-efi-autoupdate ia32 EFI compatibility

diff --git a/grub-efi-autoupdate b/grub-efi-autoupdate
--- a/grub-efi-autoupdate
+++ b/grub-efi-autoupdate
@@ -18,11 +18,11 @@ fi
 
 DIST="${GRUB_BOOTLOADER_DIST:-$DEFAULT_DIST}"
 EFI_DIR="/boot/efi"
-GRUB_EFI="$EFI_DIR/EFI/$DIST/@GRUB_EFI_NAME@"
 GRUB_CFG="$EFI_DIR/EFI/$DIST/grub.cfg"
 
-if [ ! -f "$GRUB_EFI" ]; then
-	echo "$GRUB_EFI missing, nothing to update"
+if ! stat $EFI_DIR/EFI/$DIST/grub*.efi > /dev/null 2>&1; then
+	echo "$EFI_DIR/EFI/$DIST/grub*.efi is missing, nothing to update."
+	echo "Please run grub-install"
 	exit 0
 fi
 
